services:

  # API
  repo-doc-backend:
    image: repo-doc-backend-dev
    extends:
      file: docker-compose.yml
      service: repo-doc-backend
    build:
      context: ./backend
      dockerfile: dev.Dockerfile
      # args:
      #   - SSH_CONFIG=${SSH_CONFIG}
      #   - SSH_PRIVATE_KEY=${SSH_PRIVATE_KEY}
    volumes:
      - './backend:/app'
    environment:
      - BACKEND_DEBUG=true
    ports:
      - "127.0.0.1:8000:8000"
  # Frontend
  repo-doc-ui:
    image: repo-doc-ui-dev
    extends:
      file: docker-compose.yml
      service: repo-doc-ui
    build:
      context: ./frontend
      dockerfile: dev.Dockerfile
    volumes:
      - './frontend:/app'
    environment:
      - 'VITE_APP_BACKEND_HOST='
      - 'VITE_APP_BACKEND_PORT=8000'
      - 'VITE_APP_API_KEY=${API_KEY}'
    ports:
      - "127.0.0.1:${UI_PORT:-3001}:3000"

volumes:
  repo-doc-data:
